version: '3'

services:
  db:
    image: postgis/postgis:14-3.1-alpine
    ports:
      - "60052:5432"
    volumes:
      # The default postgis script is -> /docker-entrypoint-initdb.d/10_postgis.sh
      - ./db/11_init_table.sh:/docker-entrypoint-initdb.d/11_init_table.sh
    environment:
      POSTGRES_USER: location_api_db_user
      POSTGRES_PASSWORD: location_api_db_pass
      POSTGRES_DB: location_api_db
      LANG: en_US.UTF-8

  app:
    build: .
    ports:
      - "60051:8080"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://location_api_db_user:location_api_db_pass@db:5432/location_api_db