apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  ports:
    - name: "zookeeper-server-port"
      port: 2181
      nodePort: 31001
    - name: "broker-server-port"
      port: 29092
      nodePort: 31002
    - name: "person-api-port"
      port: 30050
      nodePort: 30001
    - name: "location-api-port"
      port: 30060
      nodePort: 30002
    - name: "connection-api-port"
      port: 30070
      nodePort: 30003
  selector:
    service: udaconnect-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api
  template:
    metadata:
      labels:
        service: udaconnect-api
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:6.2.1
          name: zookeeper-server
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
        - image: confluentinc/cp-kafka:6.2.1
          name: broker-server
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_BROKER_ID
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            - name: KAFKA_JMX_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_JMX_PORT
            - name: KAFKA_JMX_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_JMX_HOSTNAME
        - image: minorpatch/udaconnect-person-api
          name: udaconnect-person-api
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: KAFKA_SERVER
            - name: KAFKA_TOPIC
              value: "Persons"
          livenessProbe:
            httpGet:
              path: /health
              port: 30050
        - image: minorpatch/udaconnect-location-api
          name: udaconnect-location-api
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:30060",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
        - image: minorpatch/udaconnect-connection-api
          name: udaconnect-connection-api
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: PERSON_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: PERSON_API_ENDPOINT
            - name: LOCATION_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: LOCATION_API_ENDPOINT
          livenessProbe:
            httpGet:
              path: /health
              port: 30070
      restartPolicy: Always
