---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-kafka-consumer
  name: udaconnect-person-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-kafka-consumer
  template:
    metadata:
      labels:
        service: udaconnect-person-kafka-consumer
    spec:
      containers:
        - image: minorpatch/udaconnect-person-kafka-consumer
          name: udaconnect-person-kafka-consumer
          imagePullPolicy: Always
          env:
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: KAFKA_SERVER
            - name: KAFKA_TOPIC
              value: "Persons"
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always
