apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
    - name: "app-port"
      port: 80
      nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
        - image: minorpatch/udaconnect-app
          name: udaconnect-app
          imagePullPolicy: Always
          env:
            - name: REACT_APP_PERSON_API_URL
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: PERSON_API_ENDPOINT
            - name: REACT_APP_CONNECTION_API_URL
              valueFrom:
                configMapKeyRef:
                  name: micro-env
                  key: LOCATION_API_ENDPOINT
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
