version: "3"

services:
  db:
    image: postgres:alpine
    ports:
      - "30052:5432"
    volumes:
      # The default postgis script is -> /docker-entrypoint-initdb.d/10_postgis.sh
      - ./db/11_init_table.sh:/docker-entrypoint-initdb.d/11_init_table.sh
    environment:
      POSTGRES_USER: person_api_db_user
      POSTGRES_PASSWORD: person_api_db_pass
      POSTGRES_DB: person_api_db

  app:
    build: .
    ports:
      - "30051:8080"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://person_api_db_user:person_api_db_pass@db:5432/person_api_db
